package net.neoforged.moddevgradle.legacyforge.internal;

/**
 * Describes "old" Minecraft versions.
 */
public record MinecraftVersion(String id, int javaVersion) {
    public static MinecraftVersion latestSupported() {
        return SUPPORTED_VERSIONS[0];
    }

    public static final MinecraftVersion[] SUPPORTED_VERSIONS = {
            new MinecraftVersion("1.21.1", 21),
            new MinecraftVersion("1.21", 21),
            new MinecraftVersion("1.20.6", 21),
            new MinecraftVersion("1.20.5", 21),
            new MinecraftVersion("1.20.4", 17),
            new MinecraftVersion("1.20.3", 17),
            new MinecraftVersion("1.20.2", 17),
            new MinecraftVersion("1.20.1", 17),
            new MinecraftVersion("1.20", 17),
            new MinecraftVersion("1.19.4", 17),
            new MinecraftVersion("1.19.3", 17),
            new MinecraftVersion("1.19.2", 17),
            new MinecraftVersion("1.19.1", 17),
            new MinecraftVersion("1.19", 17),
            new MinecraftVersion("1.18.2", 17),
            new MinecraftVersion("1.18.1", 17),
            new MinecraftVersion("1.18", 17),
            new MinecraftVersion("1.17.1", 16),
            new MinecraftVersion("1.17", 16),
            new MinecraftVersion("1.16.5", 8),
            new MinecraftVersion("1.16.4", 8),
            new MinecraftVersion("1.16.3", 8),
            new MinecraftVersion("1.16.2", 8),
            new MinecraftVersion("1.16.1", 8),
            new MinecraftVersion("1.16", 8),
            new MinecraftVersion("1.15.2", 8),
            new MinecraftVersion("1.15.1", 8),
            new MinecraftVersion("1.15", 8),
            new MinecraftVersion("1.14.4", 8),
            new MinecraftVersion("1.14.3", 8),
            new MinecraftVersion("1.14.2", 8),
            new MinecraftVersion("1.14.1", 8),
            new MinecraftVersion("1.14", 8),
            new MinecraftVersion("1.13.2", 8),
            new MinecraftVersion("1.13.1", 8),
            new MinecraftVersion("1.13", 8),
            new MinecraftVersion("1.12.2", 8),
            new MinecraftVersion("1.12.1", 8),
            new MinecraftVersion("1.12", 8),
            new MinecraftVersion("1.11.2", 8),
            new MinecraftVersion("1.11.1", 8),
            new MinecraftVersion("1.11", 8),
            new MinecraftVersion("1.10.2", 8),
            new MinecraftVersion("1.10.1", 8),
            new MinecraftVersion("1.10", 8),
            new MinecraftVersion("1.9.4", 8),
            new MinecraftVersion("1.9.3", 8),
            new MinecraftVersion("1.9.2", 8),
            new MinecraftVersion("1.9.1", 8),
            new MinecraftVersion("1.9", 8),
            new MinecraftVersion("1.8.9", 8),
            new MinecraftVersion("1.8.8", 8),
            new MinecraftVersion("1.8.7", 8),
            new MinecraftVersion("1.8.6", 8),
            new MinecraftVersion("1.8.5", 8),
            new MinecraftVersion("1.8.4", 8),
            new MinecraftVersion("1.8.3", 8),
            new MinecraftVersion("1.8.2", 8),
            new MinecraftVersion("1.8.1", 8),
            new MinecraftVersion("1.8", 8),
            new MinecraftVersion("1.7.10", 8),
            new MinecraftVersion("1.7.9", 8),
            new MinecraftVersion("1.7.8", 8),
            new MinecraftVersion("1.7.7", 8),
            new MinecraftVersion("1.7.6", 8),
            new MinecraftVersion("1.7.5", 8),
            new MinecraftVersion("1.7.4", 8),
            new MinecraftVersion("1.7.3", 8),
            new MinecraftVersion("1.7.2", 8),
            new MinecraftVersion("1.5.2", 8),
            new MinecraftVersion("1.5.1", 8),
            new MinecraftVersion("1.4.7", 8),
            new MinecraftVersion("1.4.6", 8),
            new MinecraftVersion("1.4.5", 8),
            new MinecraftVersion("1.4.4", 8),
            new MinecraftVersion("1.4.2", 8),
            new MinecraftVersion("1.3.2", 8),
            new MinecraftVersion("1.3.1", 8),
            new MinecraftVersion("1.2.5", 8),
            new MinecraftVersion("1.2.4", 8),
            new MinecraftVersion("1.2.3", 8),
            new MinecraftVersion("1.2.2", 8),
            new MinecraftVersion("1.2.1", 8),
            new MinecraftVersion("1.1", 8),
            new MinecraftVersion("1.0", 8),
    };
}
