plugins {
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge'
}

repositories {
    maven {url = "https://maven.minecraftforge.net"}
}

group = 'com.example.legacy'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

legacyForge {
    //mcpVersion = '1.20.6'
    enable {
        mcpVersion = "1.20.6"
        disableRecompilation = true
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url file('local')
        }
    }
}
